-- +goose Up
CREATE TABLE WEB_APPS (
	ID TEXT PRIMARY KEY,
	NAME TEXT NOT NULL,
	URL TEXT NOT NULL,
	USER_EMAIL TEXT NOT NULL,
	CREATED_AT INTEGER NOT NULL,
	MODIFIED_AT INTEGER NOT NULL,
	FOREIGN KEY (USER_EMAIL) REFERENCES USERS (EMAIL)
);

CREATE INDEX
	WEB_APPS_USER_EMAIL
ON
	WEB_APPS (USER_EMAIL);

CREATE INDEX
	WEB_APPS_NAME
ON
	WEB_APPS (NAME);

-- +goose Down
DROP TABLE WEB_APPS;
