-- +goose Up
CREATE TABLE NEW_WEB_APPS (
	ID TEXT PRIMARY KEY,
	NAME TEXT NOT NULL,
	URL TEXT NOT NULL,
    STATUS INTEGER NOT NULL,
    INTERVAL TEXT NOT NULL,
	USER_EMAIL TEXT NOT NULL,
	CREATED_AT INTEGER NOT NULL,
	MODIFIED_AT INTEGER NOT NULL,
	FOREIGN KEY (USER_EMAIL) REFERENCES USERS (EMAIL)
);

INSERT INTO NEW_WEB_APPS (
	ID,
	NAME,
	URL,
    STATUS,
    INTERVAL,
	USER_EMAIL,
	CREATED_AT,
	MODIFIED_AT
) SELECT
    ID,
    NAME,
    URL,
    200,
    '1H',
    USER_EMAIL,
    CREATED_AT,
    MODIFIED_AT
FROM
    WEB_APPS;

DROP TABLE WEB_APPS;

ALTER TABLE
    NEW_WEB_APPS
RENAME TO
    WEB_APPS;

CREATE INDEX
	WEB_APPS_USER_EMAIL
ON
	WEB_APPS (USER_EMAIL);

CREATE INDEX
	WEB_APPS_NAME
ON
	WEB_APPS (NAME);

CREATE TABLE SUBSCRIBERS (
    ID INTEGER PRIMARY KEY,
    WEB_APP_ID TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    CREATED_AT INTEGER NOT NULL,
    MODIFIED_AT INTEGER NOT NULL,
    FOREIGN KEY (WEB_APP_ID) REFERENCES WEB_APPS (ID)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX
    SUBSCRIBERS_WEB_APP_ID_EMAIL
ON
    SUBSCRIBERS (WEB_APP_ID, EMAIL);

-- +goose Down
DROP TABLE SUBSCRIBERS;

CREATE TABLE OLD_WEB_APPS (
	ID TEXT PRIMARY KEY,
	NAME TEXT NOT NULL,
	URL TEXT NOT NULL,
	USER_EMAIL TEXT NOT NULL,
	CREATED_AT INTEGER NOT NULL,
	MODIFIED_AT INTEGER NOT NULL,
	FOREIGN KEY (USER_EMAIL) REFERENCES USERS (EMAIL)
);

INSERT INTO OLD_WEB_APPS (
	ID,
	NAME,
	URL,
	USER_EMAIL,
	CREATED_AT,
	MODIFIED_AT
) SELECT
    ID,
    NAME,
    URL,
    USER_EMAIL,
    CREATED_AT,
    MODIFIED_AT
FROM
    WEB_APPS;

DROP TABLE WEB_APPS;

ALTER TABLE
    OLD_WEB_APPS
RENAME TO
    WEB_APPS;

CREATE INDEX
	WEB_APPS_USER_EMAIL
ON
	WEB_APPS (USER_EMAIL);

CREATE INDEX
	WEB_APPS_NAME
ON
	WEB_APPS (NAME);
