-- +goose Up
CREATE TABLE USERS (
    EMAIL TEXT NOT NULL PRIMARY KEY,
    "PASSWORD" TEXT NOT NULL,
    CREATED_AT INTEGER NOT NULL,
    MODIFIED_AT INTEGER NOT NULL
);

-- +goose Down
DROP TABLE USERS;
