logs:
  file-enabled: false
  max-size: 10
  max-age: 30

server:
  host: "0.0.0.0"
  port: "8080"

database:
  file: "./data/app.db"

authorization:
  secret: "9430be4b-ad7d-4168-87c6-ef57f889499b"
  expires-after: 12
  over-https: false
  sign-up:
    enabled: true

retention:
  enabled: false
  older-than: 30

smtp:
  enabled: false
  host: "smtp"
  port: 1025
  user: "no-reply@houston.com"
  from: "Houston <no-reply@houston.com>"
